/*
 * PhaseonWavetable.hpp — Wavetable storage and interpolated lookup
 *
 * Each Wavetable is a 2D array: frames × samples.
 * Frame interpolation (morph) + phase interpolation for smooth playback.
 * Designed for loading from single-cycle WAV files.
 *
 * Copyright (c) 2026 Bemushroomed.  All rights reserved.
 * Proprietary — not licensed under GPL or any open-source license.
 */
#pragma once
#include <cmath>
#include <cstring>
#include <vector>
#include <string>
#include <algorithm>

namespace phaseon {

// ─── Single wavetable ───────────────────────────────────────────────
// data layout: frames[frameCount][frameSize] stored flat in `data`.
struct Wavetable {
    std::string name;
    int   frameSize  = 0;       // samples per frame (e.g. 2048)
    int   frameCount = 0;       // number of frames (morph positions)
    std::vector<float> data;    // flat: frameCount * frameSize

    // Mipmapped bandlimited variants (level 0 = `data`)
    // mipData[level-1] holds frameCount * frameSize samples.
    std::vector<std::vector<float>> mipData;

    int mipCount() const { return 1 + (int)mipData.size(); }

    const float* levelData(int level) const {
        if (level <= 0 || mipData.empty()) return data.data();
        int idx = level - 1;
        if (idx < 0) idx = 0;
        if (idx >= (int)mipData.size()) idx = (int)mipData.size() - 1;
        return mipData[idx].data();
    }

    // ── Lookup ──────────────────────────────────────────────────────
    // phase01: oscillator phase 0..1 (wraps)
    // framePos: wavetable morph position 0..1
    // Returns interpolated sample.
    float sample(float phase01, float framePos) const {
        return sampleMip(phase01, framePos, 0);
    }

    float sampleMip(float phase01, float framePos, int mipLevel) const {
        if (frameCount <= 0 || frameSize <= 0) return 0.0f;

        // Clamp frame position
        framePos = std::max(0.0f, std::min(1.0f, framePos));
        float fFrame = framePos * (float)(frameCount - 1);
        int frame0 = (int)fFrame;
        int frame1 = frame0 + 1;
        float frameFrac = fFrame - (float)frame0;
        if (frame0 < 0) { frame0 = 0; frameFrac = 0.0f; }
        if (frame1 >= frameCount) { frame1 = frameCount - 1; }

        // Phase to sample index
        phase01 -= (float)(int)phase01;
        if (phase01 < 0.0f) phase01 += 1.0f;
        float fIdx = phase01 * (float)frameSize;
        int idx0 = (int)fIdx;
        float idxFrac = fIdx - (float)idx0;
        int idx1 = idx0 + 1;
        if (idx0 >= frameSize) idx0 -= frameSize;
        if (idx1 >= frameSize) idx1 -= frameSize;

        // Bilinear interpolation: phase × frame
        const float* base = levelData(mipLevel);
        const float* f0 = base + frame0 * frameSize;
        const float* f1 = base + frame1 * frameSize;
        float s0 = f0[idx0] + (f0[idx1] - f0[idx0]) * idxFrac;
        float s1 = f1[idx0] + (f1[idx1] - f1[idx0]) * idxFrac;
        return s0 + (s1 - s0) * frameFrac;
    }

    // Conservative mip selector (higher level = fewer harmonics)
    int pickMipLevel(float freqHz, float sampleRate, float brightnessBias = 1.0f) const {
        if (frameSize <= 0) return 0;
        int maxLevel = std::max(0, mipCount() - 1);
        if (maxLevel <= 0) return 0;

        float f = std::max(1.0f, freqHz);
        float sr = std::max(1.0f, sampleRate);
        float bias = std::max(0.5f, brightnessBias);
        // Treat higher brightness as effectively higher pitch (more conservative)
        f *= bias;

        // Estimated maximum safe harmonic count at this pitch
        float h = (sr * 0.5f) / f;
        // Guard: FM sidebands can exceed this; keep a safety margin
        h *= 0.7f;
        float baseH = (float)frameSize * 0.5f;
        if (h >= baseH) return 0;
        if (h < 8.0f) h = 8.0f;

        // Choose level so that baseH / 2^level <= h
        float ratio = baseH / h;
        int level = (int)std::ceil(std::log2(ratio));
        if (level < 0) level = 0;
        if (level > maxLevel) level = maxLevel;
        return level;
    }
};

// ─── Wavetable bank (holds all loaded tables) ───────────────────────
struct WavetableBank {
    std::vector<Wavetable> tables;

    // Number of tables that were generated by generateBuiltins().
    // Any tables appended afterwards are treated as user-loaded.
    int builtinCount = 0;

    int count() const { return (int)tables.size(); }

    const Wavetable* get(int index) const {
        if (index < 0 || index >= (int)tables.size()) return nullptr;
        return &tables[index];
    }

    // Add a table and return its index
    int addTable(Wavetable&& wt) {
        int idx = (int)tables.size();
        tables.push_back(std::move(wt));
        return idx;
    }

    // ── Built-in table generation ───────────────────────────────────
    // Creates a set of code-generated fallback tables so the module
    // always produces sound even without external WAV files.
    void generateBuiltins();

    // ── WAV loading ─────────────────────────────────────────────────
    // Load a single-cycle wavetable from a WAV file.
    // If the file contains N × frameSize samples, it's treated as N frames.
    // Returns the table index, or -1 on failure.
    int loadFromWav(const std::string& path, int expectedFrameSize = 2048);
};

} // namespace phaseon
